version: '3.7'
services:
  db:
    image: mongo:latest

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db:/db
      - ./doc:/doc
    ports:
      - 16761:16761
    depends_on:
      - 'db'
    command: ['/app/build/apiserver', '-cfg', '/app/config.json']
